name: Docker Image CI
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
    - name: Build the Docker image
      run: docker build . --tag ${{secrets.DOCKER_USER}}/nfeminer:latest
    - name: Pushing to Github
      run: docker push ${{secrets.DOCKER_USER}}/nfeminer:latest
