name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Docker build and push
      uses: cloudposse/github-action-docker-build-push@1.14.0
      with:
        organization: 'arthurd2'
        repository: 'nfeminer'
        image_name: 'arthurd2/nfeminer'
        registry: registry.hub.docker.com
        login: 'arthurd2'
        password: ${{secrets.DOCKER_PASS}}
